# Generated by Django 4.1.7 on 2023-02-27 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Programs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("program_name", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=100)),
                ("program_url", models.URLField()),
            ],
            options={
                "ordering": ["-program_name"],
            },
        ),
        migrations.CreateModel(
            name="Inscope",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=100)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.programs"
                    ),
                ),
            ],
        ),
    ]
